drop table if exists BUDDY_PAIR;
drop table if exists PEER_LANGUAGE_PREFERENCE;
drop table if exists ERASMUS_LANGUAGE_PREFERENCE;
drop table if exists PEER;
drop table if exists ERASMUS;
drop table if exists STUDENT;
drop table if exists FACULTY;
drop table if exists STUDIES;
drop table if exists LANGUAGE;
drop table if exists COUNTRY;

create table COUNTRY (
	country_code varchar(2) primary key,
	country_name varchar(125) unique not null
);

create table LANGUAGE (
	id int auto_increment primary key,
	language varchar(32) unique not null
);

create table STUDIES (
	id int auto_increment primary key,
	name varchar(64) unique not null
);

create table FACULTY (
	id int auto_increment primary key,
	name varchar(64) unique not null
);

create table STUDENT (
	id int auto_increment primary key,
	name varchar(128) not null,
	surname varchar(256) not null,
	gender boolean not null,
	birthdate date not null,
	nacionality varchar(2) not null,
	aegee_member boolean not null default FALSE,
	email varchar(128) unique not null,
	phone varchar(16),
	studies int,
	faculty int,
	foreign key (nacionality) references COUNTRY(country_code),
	foreign key (studies) references STUDIES(id),
	foreign key (faculty) references FACULTY(id)
);

create table ERASMUS (
	id int auto_increment primary key,
	register_date timestamp default current_timestamp,
	erasmus int unique not null,
	gender_preference boolean,
	arrival_date datetime,
	notes varchar(1024),
	foreign key (erasmus) references STUDENT(id)
		on delete cascade
);

-- TODO: add NIP (optional)
create table PEER (
	id int auto_increment primary key,
	register_date timestamp default current_timestamp,
	peer int unique not null,
	gender_preference boolean,
	erasmus_limit int not null check(erasmus_limit > 0),
	notes varchar(1024),
	foreign key (peer) references STUDENT(id)
		on delete cascade
);

create table ERASMUS_LANGUAGE_PREFERENCE (
	erasmus int not null,
	language int not null,
	foreign key (erasmus) references ERASMUS(id)
		on delete cascade,
	foreign key (language) references LANGUAGE(id)
		on delete cascade
);

create table PEER_LANGUAGE_PREFERENCE (
	peer int not null,
	language int not null,
	foreign key (peer) references PEER(id)
		on delete cascade,
	foreign key (language) references LANGUAGE(id)
		on delete cascade
);

create table BUDDY_PAIR (
	erasmus int unique not null,
	peer int not null,
	notified_erasmus boolean not null default false,
	notified_peer boolean not null default false,
	foreign key (erasmus) references ERASMUS(id)
		on delete cascade,
	foreign key (peer) references PEER(id)
		on delete cascade
);

------------------------------------------------------------------

insert into COUNTRY values 
	('US', 'United States'),
	('CA', 'Canada'),
	('AF', 'Afghanistan'),
	('AL', 'Albania'),
	('DZ', 'Algeria'),
	('DS', 'American Samoa'),
	('AD', 'Andorra'),
	('AO', 'Angola'),
	('AI', 'Anguilla'),
	('AQ', 'Antarctica'),
	('AG', 'Antigua and/or Barbuda'),
	('AR', 'Argentina'),
	('AM', 'Armenia'),
	('AW', 'Aruba'),
	('AU', 'Australia'),
	('AT', 'Austria'),
	('AZ', 'Azerbaijan'),
	('BS', 'Bahamas'),
	('BH', 'Bahrain'),
	('BD', 'Bangladesh'),
	('BB', 'Barbados'),
	('BY', 'Belarus'),
	('BE', 'Belgium'),
	('BZ', 'Belize'),
	('BJ', 'Benin'),
	('BM', 'Bermuda'),
	('BT', 'Bhutan'),
	('BO', 'Bolivia'),
	('BA', 'Bosnia and Herzegovina'),
	('BW', 'Botswana'),
	('BV', 'Bouvet Island'),
	('BR', 'Brazil'),
	('IO', 'British lndian Ocean Territory'),
	('BN', 'Brunei Darussalam'),
	('BG', 'Bulgaria'),
	('BF', 'Burkina Faso'),
	('BI', 'Burundi'),
	('KH', 'Cambodia'),
	('CM', 'Cameroon'),
	('CV', 'Cape Verde'),
	('KY', 'Cayman Islands'),
	('CF', 'Central African Republic'),
	('TD', 'Chad'),
	('CL', 'Chile'),
	('CN', 'China'),
	('CX', 'Christmas Island'),
	('CC', 'Cocos (Keeling) Islands'),
	('CO', 'Colombia'),
	('KM', 'Comoros'),
	('CG', 'Congo'),
	('CK', 'Cook Islands'),
	('CR', 'Costa Rica'),
	('HR', 'Croatia (Hrvatska)'),
	('CU', 'Cuba'),
	('CY', 'Cyprus'),
	('CZ', 'Czech Republic'),
	('DK', 'Denmark'),
	('DJ', 'Djibouti'),
	('DM', 'Dominica'),
	('DO', 'Dominican Republic'),
	('TP', 'East Timor'),
	('EC', 'Ecuador'),
	('EG', 'Egypt'),
	('SV', 'El Salvador'),
	('GQ', 'Equatorial Guinea'),
	('ER', 'Eritrea'),
	('EE', 'Estonia'),
	('ET', 'Ethiopia'),
	('FK', 'Falkland Islands (Malvinas)'),
	('FO', 'Faroe Islands'),
	('FJ', 'Fiji'),
	('FI', 'Finland'),
	('FR', 'France'),
	('FX', 'France, Metropolitan'),
	('GF', 'French Guiana'),
	('PF', 'French Polynesia'),
	('TF', 'French Southern Territories'),
	('GA', 'Gabon'),
	('GM', 'Gambia'),
	('GE', 'Georgia'),
	('DE', 'Germany'),
	('GH', 'Ghana'),
	('GI', 'Gibraltar'),
	('GR', 'Greece'),
	('GL', 'Greenland'),
	('GD', 'Grenada'),
	('GP', 'Guadeloupe'),
	('GU', 'Guam'),
	('GT', 'Guatemala'),
	('GN', 'Guinea'),
	('GW', 'Guinea-Bissau'),
	('GY', 'Guyana'),
	('HT', 'Haiti'),
	('HM', 'Heard and Mc Donald Islands'),
	('HN', 'Honduras'),
	('HK', 'Hong Kong'),
	('HU', 'Hungary'),
	('IS', 'Iceland'),
	('IN', 'India'),
	('ID', 'Indonesia'),
	('IR', 'Iran (Islamic Republic of)'),
	('IQ', 'Iraq'),
	('IE', 'Ireland'),
	('IL', 'Israel'),
	('IT', 'Italy'),
	('CI', 'Ivory Coast'),
	('JM', 'Jamaica'),
	('JP', 'Japan'),
	('JO', 'Jordan'),
	('KZ', 'Kazakhstan'),
	('KE', 'Kenya'),
	('KI', 'Kiribati'),
	('KP', 'Korea, Democratic People''s Republic of'),
	('KR', 'Korea, Republic of'),
	('XK', 'Kosovo'),
	('KW', 'Kuwait'),
	('KG', 'Kyrgyzstan'),
	('LA', 'Lao People''s Democratic Republic'),
	('LV', 'Latvia'),
	('LB', 'Lebanon'),
	('LS', 'Lesotho'),
	('LR', 'Liberia'),
	('LY', 'Libyan Arab Jamahiriya'),
	('LI', 'Liechtenstein'),
	('LT', 'Lithuania'),
	('LU', 'Luxembourg'),
	('MO', 'Macau'),
	('MK', 'Macedonia'),
	('MG', 'Madagascar'),
	('MW', 'Malawi'),
	('MY', 'Malaysia'),
	('MV', 'Maldives'),
	('ML', 'Mali'),
	('MT', 'Malta'),
	('MH', 'Marshall Islands'),
	('MQ', 'Martinique'),
	('MR', 'Mauritania'),
	('MU', 'Mauritius'),
	('TY', 'Mayotte'),
	('MX', 'Mexico'),
	('FM', 'Micronesia, Federated States of'),
	('MD', 'Moldova, Republic of'),
	('MC', 'Monaco'),
	('MN', 'Mongolia'),
	('ME', 'Montenegro'),
	('MS', 'Montserrat'),
	('MA', 'Morocco'),
	('MZ', 'Mozambique'),
	('MM', 'Myanmar'),
	('NA', 'Namibia'),
	('NR', 'Nauru'),
	('NP', 'Nepal'),
	('NL', 'Netherlands'),
	('AN', 'Netherlands Antilles'),
	('NC', 'New Caledonia'),
	('NZ', 'New Zealand'),
	('NI', 'Nicaragua'),
	('NE', 'Niger'),
	('NG', 'Nigeria'),
	('NU', 'Niue'),
	('NF', 'Norfork Island'),
	('MP', 'Northern Mariana Islands'),
	('NO', 'Norway'),
	('OM', 'Oman'),
	('PK', 'Pakistan'),
	('PW', 'Palau'),
	('PA', 'Panama'),
	('PG', 'Papua New Guinea'),
	('PY', 'Paraguay'),
	('PE', 'Peru'),
	('PH', 'Philippines'),
	('PN', 'Pitcairn'),
	('PL', 'Poland'),
	('PT', 'Portugal'),
	('PR', 'Puerto Rico'),
	('QA', 'Qatar'),
	('RE', 'Reunion'),
	('RO', 'Romania'),
	('RU', 'Russian Federation'),
	('RW', 'Rwanda'),
	('KN', 'Saint Kitts and Nevis'),
	('LC', 'Saint Lucia'),
	('VC', 'Saint Vincent and the Grenadines'),
	('WS', 'Samoa'),
	('SM', 'San Marino'),
	('ST', 'Sao Tome and Principe'),
	('SA', 'Saudi Arabia'),
	('SN', 'Senegal'),
	('RS', 'Serbia'),
	('SC', 'Seychelles'),
	('SL', 'Sierra Leone'),
	('SG', 'Singapore'),
	('SK', 'Slovakia'),
	('SI', 'Slovenia'),
	('SB', 'Solomon Islands'),
	('SO', 'Somalia'),
	('ZA', 'South Africa'),
	('GS', 'South Georgia South Sandwich Islands'),
	('ES', 'Spain'),
	('LK', 'Sri Lanka'),
	('SH', 'St. Helena'),
	('PM', 'St. Pierre and Miquelon'),
	('SD', 'Sudan'),
	('SR', 'Suriname'),
	('SJ', 'Svalbarn and Jan Mayen Islands'),
	('SZ', 'Swaziland'),
	('SE', 'Sweden'),
	('CH', 'Switzerland'),
	('SY', 'Syrian Arab Republic'),
	('TW', 'Taiwan'),
	('TJ', 'Tajikistan'),
	('TZ', 'Tanzania, United Republic of'),
	('TH', 'Thailand'),
	('TG', 'Togo'),
	('TK', 'Tokelau'),
	('TO', 'Tonga'),
	('TT', 'Trinidad and Tobago'),
	('TN', 'Tunisia'),
	('TR', 'Turkey'),
	('TM', 'Turkmenistan'),
	('TC', 'Turks and Caicos Islands'),
	('TV', 'Tuvalu'),
	('UG', 'Uganda'),
	('UA', 'Ukraine'),
	('AE', 'United Arab Emirates'),
	('GB', 'United Kingdom'),
	('UM', 'United States minor outlying islands'),
	('UY', 'Uruguay'),
	('UZ', 'Uzbekistan'),
	('VU', 'Vanuatu'),
	('VA', 'Vatican City State'),
	('VE', 'Venezuela'),
	('VN', 'Vietnam'),
	('VG', 'Virgin Islands (British)'),
	('VI', 'Virgin Islands (U.S.)'),
	('WF', 'Wallis and Futuna Islands'),
	('EH', 'Western Sahara'),
	('YE', 'Yemen'),
	('YU', 'Yugoslavia'),
	('ZR', 'Zaire'),
	('ZM', 'Zambia'),
	('ZW', 'Zimbabwe');

insert into LANGUAGE (language) values 
	('Abhyasi'),
	('Acholi'),
	('Adja'),
	('Afar'),
	('Afrikaans'),
	('Aimará'),
	('Ainu'),
	('Aizo'),
	('Akan'),
	('Albaniana'),
	('Ambo'),
	('Amhara'),
	('Ami'),
	('Ane'),
	('Arabic'),
	('Arabic-French'),
	('Arabic-French-English'),
	('Araucan'),
	('Arawakan'),
	('Armenian'),
	('Asami'),
	('Assyrian'),
	('Atayal'),
	('Avarian'),
	('Azerbaijani'),
	('Bajad'),
	('Bajan'),
	('Bakhtyari'),
	('Balante'),
	('Bali'),
	('Balochi'),
	('Bambara'),
	('Bamileke-bamum'),
	('Banda'),
	('Banja'),
	('Bari'),
	('Bariba'),
	('Bashkir'),
	('Basque'),
	('Bassa'),
	('Batakki'),
	('Beja'),
	('Belorussian'),
	('Bemba'),
	('Bengali'),
	('Berberi'),
	('Bhojpuri'),
	('Bicol'),
	('Bilin'),
	('Bislama'),
	('Boa'),
	('Brahui'),
	('Bubi'),
	('Bugi'),
	('Bulgariana'),
	('Bullom-sherbro'),
	('Bura'),
	('Burmese'),
	('Buryat'),
	('Busansi'),
	('Cakchiquel'),
	('Canton Chinese'),
	('Caprivi'),
	('Caribbean'),
	('Carolinian'),
	('Catalan'),
	('Cebuano'),
	('Chaga and Pare'),
	('Chakma'),
	('Chamorro'),
	('Chechen'),
	('Chewa'),
	('Chibcha'),
	('Chichewa'),
	('Chilluk'),
	('Chin'),
	('Chinese'),
	('Chiu chau'),
	('Chokwe'),
	('Chuabo'),
	('Chuvash'),
	('Circassian'),
	('Comorian'),
	('Comorian-Arabic'),
	('Comorian-French'),
	('Comorian-Swahili'),
	('Comorian-madagassi'),
	('Creole English'),
	('Creole French'),
	('Crioulo'),
	('Cuna'),
	('Czech and Moravian'),
	('Czech'),
	('Dagara'),
	('Danish'),
	('Dari'),
	('Dariganga'),
	('Dhivehi'),
	('Dinka'),
	('Diola'),
	('Dong'),
	('Dorbet'),
	('Duala'),
	('Dusun'),
	('Dutch'),
	('Dyula'),
	('Dzongkha'),
	('Edo'),
	('Embera'),
	('English'),
	('Eskimo Languages'),
	('Estonian'),
	('Ewe'),
	('Fang'),
	('Faroese'),
	('Fijian'),
	('Finnish'),
	('Fon'),
	('French'),
	('Fries'),
	('Friuli'),
	('Fukien'),
	('Ful'),
	('Fur'),
	('Futuna'),
	('Ga-adangme'),
	('Gaeli'),
	('Gagauzi'),
	('Galecian'),
	('Ganda'),
	('Garifuna'),
	('Garo'),
	('Gbaya'),
	('Georgiana'),
	('German'),
	('Gilaki'),
	('Gio'),
	('Gisu'),
	('Goajiro'),
	('Gogo'),
	('Gorane'),
	('Grebo'),
	('Greek'),
	('Greenlandic'),
	('Guaraní'),
	('Guaymí'),
	('Gujarati'),
	('Gur'),
	('Gurage'),
	('Gurma'),
	('Gusii'),
	('Ha'),
	('Hadareb'),
	('Hadjarai'),
	('Haiti Creole'),
	('Hakka'),
	('Hassaniya'),
	('Hausa'),
	('Haya'),
	('Hebrew'),
	('Hehet'),
	('Herero'),
	('Hiligaynon'),
	('Hindi'),
	('Hindko'),
	('Hui'),
	('Hungarian'),
	('Iban'),
	('Ibibio'),
	('Ibo'),
	('Icelandic'),
	('Ijo'),
	('Ilocano'),
	('Indian Languages'),
	('Irish'),
	('Italian'),
	('Japanese'),
	('Javanese'),
	('Joruba'),
	('Kabyé'),
	('Kachin'),
	('Kalenjin'),
	('Kamba'),
	('Kanem-bornu'),
	('Kannada'),
	('Kanuri'),
	('Karakalpak'),
	('Karen'),
	('Kavango'),
	('Kayah'),
	('Kazakh'),
	('Kekchí'),
	('Ketšua'),
	('Khasi'),
	('Khmer'),
	('Khoekhoe'),
	('Kiga'),
	('Kikuyu'),
	('Kirgiz'),
	('Kiribati'),
	('Kirundi'),
	('Kissi'),
	('Kongo'),
	('Kono-vai'),
	('Korean'),
	('Kosrean'),
	('Kotokoli'),
	('Kpelle'),
	('Kru'),
	('Kuranko'),
	('Kurdish'),
	('Kuy'),
	('Kymri'),
	('Lango'),
	('Lao'),
	('Lao-Soung'),
	('Latvian'),
	('Lezgian'),
	('Limba'),
	('Lithuanian'),
	('Loma'),
	('Lomwe'),
	('Lotuko'),
	('Lozi'),
	('Luba'),
	('Luchazi'),
	('Lugbara'),
	('Luguru'),
	('Luhya'),
	('Luimbe-nganguela'),
	('Luo'),
	('Luri'),
	('Luvale'),
	('Luxembourgish'),
	('Macedonian'),
	('Madura'),
	('Maguindanao'),
	('Mahoré'),
	('Maithili'),
	('Maka'),
	('Makonde'),
	('Makua'),
	('Malagasy'),
	('Malajalam'),
	('Malay'),
	('Malay-English'),
	('Malenasian Languages'),
	('Malinke'),
	('Maltese'),
	('Mam'),
	('Man'),
	('Mandara'),
	('Mandarin Chinese'),
	('Mandjia'),
	('Mandyako'),
	('Mano'),
	('Mantšu'),
	('Maori'),
	('Maranao'),
	('Marathi'),
	('Marendje'),
	('Mari'),
	('Marma'),
	('Marshallese'),
	('Masai'),
	('Masana'),
	('Maya Languages'),
	('Mayo-kebbi'),
	('Mazandarani'),
	('Mbete'),
	('Mboshi'),
	('Mbum'),
	('Mbundu'),
	('Mende'),
	('Meru'),
	('Miao'),
	('Min'),
	('Minangkabau'),
	('Miskito'),
	('Mixed Languages'),
	('Mixtec'),
	('Moba'),
	('Mon'),
	('Mon-khmer'),
	('Monegasque'),
	('Mongo'),
	('Mongolian'),
	('Moravian'),
	('Mordva'),
	('Mortlock'),
	('Mossi'),
	('Mpongwe'),
	('Muong'),
	('Nahua'),
	('Nama'),
	('Naudemba'),
	('Nauru'),
	('Ndebele'),
	('Nepali'),
	('Newari'),
	('Ngala and Bangi'),
	('Ngbaka'),
	('Ngoni'),
	('Niue'),
	('Nkole'),
	('Northsotho'),
	('Norwegian'),
	('Nsenga'),
	('Nubian Languages'),
	('Nuer'),
	('Nung'),
	('Nyakusa'),
	('Nyamwesi'),
	('Nyaneka-nkhumbi'),
	('Nyanja'),
	('Nyika'),
	('Náhuatl'),
	('Orija'),
	('Oromo'),
	('Osseetti'),
	('Otomí'),
	('Ouaddai'),
	('Ovambo'),
	('Ovimbundu'),
	('Paiwan'),
	('Palau'),
	('Pampango'),
	('Pangasinan'),
	('Papiamento'),
	('Papuan Languages'),
	('Pashto'),
	('Persian'),
	('Philippene Languages'),
	('Pilipino'),
	('Pitcairnese'),
	('Pohnpei'),
	('Polish'),
	('Polynesian Languages'),
	('Portuguese'),
	('Punjabi'),
	('Punu'),
	('Punu-sira-nzebi'),
	('Puyi'),
	('Quiché'),
	('Rakhine'),
	('Rapa nui'),
	('Romani'),
	('Romanian'),
	('Romansh'),
	('Ronga'),
	('Rundi'),
	('Russian'),
	('Rwanda'),
	('Saame'),
	('Saho'),
	('Samoan'),
	('Samoan-English'),
	('San'),
	('Sango'),
	('Santhali'),
	('Sara'),
	('Saraiki'),
	('Sardinian'),
	('Sena'),
	('Senufo and Minianka'),
	('Serbo-Croatian'),
	('Serer'),
	('Seselwa'),
	('Shambala'),
	('Shan'),
	('Shona'),
	('Sidamo'),
	('Silesiana'),
	('Sinaberberi'),
	('Sindhi'),
	('Singali'),
	('Slovak'),
	('Slovene'),
	('Soga'),
	('Somali'),
	('Somba'),
	('Songhai'),
	('Songhai-zerma'),
	('Soninke'),
	('Soqutri'),
	('Sotho'),
	('Southern Slavic Languages'),
	('Southsotho'),
	('Spanish'),
	('Sranantonga'),
	('Sumo'),
	('Sunda'),
	('Susu'),
	('Swahili'),
	('Swazi'),
	('Swedish'),
	('Tadzhik'),
	('Tagalog'),
	('Tahitian'),
	('Tamang'),
	('Tamashek'),
	('Tamil'),
	('Tandjile'),
	('Tatar'),
	('Teke'),
	('Telugu'),
	('Temne'),
	('Teso'),
	('Thai'),
	('Tharu'),
	('Tho'),
	('Tibetan'),
	('Tigre'),
	('Tigrinja'),
	('Tikar'),
	('Tiv'),
	('Tokelau'),
	('Tongan'),
	('Tripuri'),
	('Trukese'),
	('Tsonga'),
	('Tswa'),
	('Tswana'),
	('Tujia'),
	('Tukulor'),
	('Turkana'),
	('Turkish'),
	('Turkmenian'),
	('Tuvalu'),
	('Tšam'),
	('Udmur'),
	('Uighur'),
	('Ukrainian and Russian'),
	('Ukrainian'),
	('Urdu'),
	('Uzbek'),
	('Venda'),
	('Vietnamese'),
	('Walaita'),
	('Wallis'),
	('Waray-waray'),
	('Warrau'),
	('Watyi'),
	('Wolea'),
	('Wolof'),
	('Xhosa'),
	('Yalunka'),
	('Yao'),
	('Yap'),
	('Yi'),
	('Yucatec'),
	('Zande'),
	('Zapotec'),
	('Zenaga'),
	('Zhuang'),
	('Zulu'),
	('[South]Mande');

insert into STUDIES (name) values
	('Medicine / Nursing'),
	('Chemistry'),
	('Physics'),
	('Mathematics / Statistics'),
	('Geology'),
	('Veterinary'),
	('Engineering'),
	('Architecture'),
	('Business Management'),
	('Economics'),
	('Law Studies'),
	('Foreign Languages / Philology'),
	('History / Philosophy'),
	('Social Studies'),
	('Education'),
	('Other'),
	('Unknown');

insert into FACULTY (name) values
	('Campus San Francisco'),
	('Campus Rio Ebro'),
	('Campus Veterinaria'),
	('USJ - Universidad San Jorge'),
	('Campus de Huesca'),
	('Campus de Teruel'),
	('Campus de Jaca'),
	('Campus de La Almunia'),
	('Other'),
	('Unknown');
