insert into COUNTRY values 
    ('US', 'United States', 'USA'),
    ('CA', 'Canada', 'CAN'),
    ('AF', 'Afghanistan', 'AFG'),
    ('AL', 'Albania', 'ALB'),
    ('DZ', 'Algeria', 'DZA'),
    ('DS', 'American Samoa', NULL),
    ('AD', 'Andorra', 'AND'),
    ('AO', 'Angola', 'AGO'),
    ('AI', 'Anguilla', 'AIA'),
    ('AQ', 'Antarctica', 'ATA'),
    ('AG', 'Antigua and/or Barbuda', 'ATG'),
    ('AR', 'Argentina', 'ARG'),
    ('AM', 'Armenia', 'ARM'),
    ('AW', 'Aruba', 'ABW'),
    ('AU', 'Australia', 'AUS'),
    ('AT', 'Austria', 'AUT'),
    ('AZ', 'Azerbaijan', 'AZE'),
    ('BS', 'Bahamas', 'BHS'),
    ('BH', 'Bahrain', 'BHR'),
    ('BD', 'Bangladesh', 'BGD'),
    ('BB', 'Barbados', 'BRB'),
    ('BY', 'Belarus', 'BLR'),
    ('BE', 'Belgium', 'BEL'),
    ('BZ', 'Belize', 'BLZ'),
    ('BJ', 'Benin', 'BEN'),
    ('BM', 'Bermuda', 'BMU'),
    ('BT', 'Bhutan', 'BTN'),
    ('BO', 'Bolivia', 'BOL'),
    ('BA', 'Bosnia and Herzegovina', 'BIH'),
    ('BW', 'Botswana', 'BWA'),
    ('BV', 'Bouvet Island', 'BVT'),
    ('BR', 'Brazil', 'BRA'),
    ('IO', 'British lndian Ocean Territory', 'IOT'),
    ('BN', 'Brunei Darussalam', 'BRN'),
    ('BG', 'Bulgaria', 'BGR'),
    ('BF', 'Burkina Faso', 'BFA'),
    ('BI', 'Burundi', 'BDI'),
    ('KH', 'Cambodia', 'KHM'),
    ('CM', 'Cameroon', 'CMR'),
    ('CV', 'Cape Verde', 'CPV'),
    ('KY', 'Cayman Islands', 'CYM'),
    ('CF', 'Central African Republic', 'CAF'),
    ('TD', 'Chad', 'TCD'),
    ('CL', 'Chile', 'CHL'),
    ('CN', 'China', 'CHN'),
    ('CX', 'Christmas Island', 'CXR'),
    ('CC', 'Cocos (Keeling) Islands', 'CCK'),
    ('CO', 'Colombia', 'COL'),
    ('KM', 'Comoros', 'COM'),
    ('CG', 'Congo', 'COG'),
    ('CK', 'Cook Islands', 'COK'),
    ('CR', 'Costa Rica', 'CRI'),
    ('HR', 'Croatia (Hrvatska)', 'HRV'),
    ('CU', 'Cuba', 'CUB'),
    ('CY', 'Cyprus', 'CYP'),
    ('CZ', 'Czech Republic', 'CZE'),
    ('DK', 'Denmark', 'DNK'),
    ('DJ', 'Djibouti', 'DJI'),
    ('DM', 'Dominica', 'DMA'),
    ('DO', 'Dominican Republic', 'DOM'),
    ('TP', 'East Timor', NULL),
    ('EC', 'Ecuador', 'ECU'),
    ('EG', 'Egypt', 'EGY'),
    ('SV', 'El Salvador', 'SLV'),
    ('GQ', 'Equatorial Guinea', 'GNQ'),
    ('ER', 'Eritrea', 'ERI'),
    ('EE', 'Estonia', 'EST'),
    ('ET', 'Ethiopia', 'ETH'),
    ('FK', 'Falkland Islands (Malvinas)', 'FLK'),
    ('FO', 'Faroe Islands', 'FRO'),
    ('FJ', 'Fiji', 'FJI'),
    ('FI', 'Finland', 'FIN'),
    ('FR', 'France', 'FRA'),
    ('FX', 'France, Metropolitan', NULL),
    ('GF', 'French Guiana', 'GUF'),
    ('PF', 'French Polynesia', 'PYF'),
    ('TF', 'French Southern Territories', 'ATF'),
    ('GA', 'Gabon', 'GAB'),
    ('GM', 'Gambia', 'GMB'),
    ('GE', 'Georgia', 'GEO'),
    ('DE', 'Germany', 'DEU'),
    ('GH', 'Ghana', 'GHA'),
    ('GI', 'Gibraltar', 'GIB'),
    ('GR', 'Greece', 'GRC'),
    ('GL', 'Greenland', 'GRL'),
    ('GD', 'Grenada', 'GRD'),
    ('GP', 'Guadeloupe', 'GLP'),
    ('GU', 'Guam', 'GUM'),
    ('GT', 'Guatemala', 'GTM'),
    ('GN', 'Guinea', 'GIN'),
    ('GW', 'Guinea-Bissau', 'GNB'),
    ('GY', 'Guyana', 'GUY'),
    ('HT', 'Haiti', 'HTI'),
    ('HM', 'Heard and Mc Donald Islands', 'HMD'),
    ('HN', 'Honduras', 'HND'),
    ('HK', 'Hong Kong', 'HKG'),
    ('HU', 'Hungary', 'HUN'),
    ('IS', 'Iceland', 'ISL'),
    ('IN', 'India', 'IND'),
    ('ID', 'Indonesia', 'IDN'),
    ('IR', 'Iran (Islamic Republic of)', 'IRN'),
    ('IQ', 'Iraq', 'IRQ'),
    ('IE', 'Ireland', 'IRL'),
    ('IL', 'Israel', 'ISR'),
    ('IT', 'Italy', 'ITA'),
    ('CI', 'Ivory Coast', 'CIV'),
    ('JM', 'Jamaica', 'JAM'),
    ('JP', 'Japan', 'JPN'),
    ('JO', 'Jordan', 'JOR'),
    ('KZ', 'Kazakhstan', 'KAZ'),
    ('KE', 'Kenya', 'KEN'),
    ('KI', 'Kiribati', 'KIR'),
    ('KP', 'Korea, Democratic PeopleNULLs Republic of', 'PRK'),
    ('KR', 'Korea, Republic of', 'KOR'),
    ('XK', 'Kosovo', NULL),
    ('KW', 'Kuwait', 'KWT'),
    ('KG', 'Kyrgyzstan', 'KGZ'),
    ('LA', 'Lao PeopleNULLs Democratic Republic', 'LAO'),
    ('LV', 'Latvia', 'LVA'),
    ('LB', 'Lebanon', 'LBN'),
    ('LS', 'Lesotho', 'LSO'),
    ('LR', 'Liberia', 'LBR'),
    ('LY', 'Libyan Arab Jamahiriya', 'LBY'),
    ('LI', 'Liechtenstein', 'LIE'),
    ('LT', 'Lithuania', 'LTU'),
    ('LU', 'Luxembourg', 'LUX'),
    ('MO', 'Macau', 'MAC'),
    ('MK', 'Macedonia', 'MKD'),
    ('MG', 'Madagascar', 'MDG'),
    ('MW', 'Malawi', 'MWI'),
    ('MY', 'Malaysia', 'MYS'),
    ('MV', 'Maldives', 'MDV'),
    ('ML', 'Mali', 'MLI'),
    ('MT', 'Malta', 'MLT'),
    ('MH', 'Marshall Islands', 'MHL'),
    ('MQ', 'Martinique', 'MTQ'),
    ('MR', 'Mauritania', 'MRT'),
    ('MU', 'Mauritius', 'MUS'),
    ('TY', 'Mayotte', NULL),
    ('MX', 'Mexico', 'MEX'),
    ('FM', 'Micronesia, Federated States of', 'FSM'),
    ('MD', 'Moldova, Republic of', 'MDA'),
    ('MC', 'Monaco', 'MCO'),
    ('MN', 'Mongolia', 'MNG'),
    ('ME', 'Montenegro', 'MNE'),
    ('MS', 'Montserrat', 'MSR'),
    ('MA', 'Morocco', 'MAR'),
    ('MZ', 'Mozambique', 'MOZ'),
    ('MM', 'Myanmar', 'MMR'),
    ('NA', 'Namibia', 'NAM'),
    ('NR', 'Nauru', 'NRU'),
    ('NP', 'Nepal', 'NPL'),
    ('NL', 'Netherlands', 'NLD'),
    ('AN', 'Netherlands Antilles', NULL),
    ('NC', 'New Caledonia', 'NCL'),
    ('NZ', 'New Zealand', 'NZL'),
    ('NI', 'Nicaragua', 'NIC'),
    ('NE', 'Niger', 'NER'),
    ('NG', 'Nigeria', 'NGA'),
    ('NU', 'Niue', 'NIU'),
    ('NF', 'Norfork Island', 'NFK'),
    ('MP', 'Northern Mariana Islands', 'MNP'),
    ('NO', 'Norway', 'NOR'),
    ('OM', 'Oman', 'OMN'),
    ('PK', 'Pakistan', 'PAK'),
    ('PW', 'Palau', 'PLW'),
    ('PA', 'Panama', 'PAN'),
    ('PG', 'Papua New Guinea', 'PNG'),
    ('PY', 'Paraguay', 'PRY'),
    ('PE', 'Peru', 'PER'),
    ('PH', 'Philippines', 'PHL'),
    ('PN', 'Pitcairn', 'PCN'),
    ('PL', 'Poland', 'POL'),
    ('PT', 'Portugal', 'PRT'),
    ('PR', 'Puerto Rico', 'PRI'),
    ('QA', 'Qatar', 'QAT'),
    ('RE', 'Reunion', 'REU'),
    ('RO', 'Romania', 'ROU'),
    ('RU', 'Russian Federation', 'RUS'),
    ('RW', 'Rwanda', 'RWA'),
    ('KN', 'Saint Kitts and Nevis', 'KNA'),
    ('LC', 'Saint Lucia', 'LCA'),
    ('VC', 'Saint Vincent and the Grenadines', 'VCT'),
    ('WS', 'Samoa', 'WSM'),
    ('SM', 'San Marino', 'SMR'),
    ('ST', 'Sao Tome and Principe', 'STP'),
    ('SA', 'Saudi Arabia', 'SAU'),
    ('SN', 'Senegal', 'SEN'),
    ('RS', 'Serbia', 'SRB'),
    ('SC', 'Seychelles', 'SYC'),
    ('SL', 'Sierra Leone', 'SLE'),
    ('SG', 'Singapore', 'SGP'),
    ('SK', 'Slovakia', 'SVK'),
    ('SI', 'Slovenia', 'SVN'),
    ('SB', 'Solomon Islands', 'SLB'),
    ('SO', 'Somalia', 'SOM'),
    ('ZA', 'South Africa', 'ZAF'),
    ('GS', 'South Georgia South Sandwich Islands', 'SGS'),
    ('ES', 'Spain', 'ESP'),
    ('LK', 'Sri Lanka', 'LKA'),
    ('SH', 'St. Helena', 'SHN'),
    ('PM', 'St. Pierre and Miquelon', 'SPM'),
    ('SD', 'Sudan', 'SDN'),
    ('SR', 'Suriname', 'SUR'),
    ('SJ', 'Svalbarn and Jan Mayen Islands', 'SJM'),
    ('SZ', 'Swaziland', 'SWZ'),
    ('SE', 'Sweden', 'SWE'),
    ('CH', 'Switzerland', 'CHE'),
    ('SY', 'Syrian Arab Republic', 'SYR'),
    ('TW', 'Taiwan', 'TWN'),
    ('TJ', 'Tajikistan', 'TJK'),
    ('TZ', 'Tanzania, United Republic of', 'TZA'),
    ('TH', 'Thailand', 'THA'),
    ('TG', 'Togo', 'TGO'),
    ('TK', 'Tokelau', 'TKL'),
    ('TO', 'Tonga', 'TON'),
    ('TT', 'Trinidad and Tobago', 'TTO'),
    ('TN', 'Tunisia', 'TUN'),
    ('TR', 'Turkey', 'TUR'),
    ('TM', 'Turkmenistan', 'TKM'),
    ('TC', 'Turks and Caicos Islands', 'TCA'),
    ('TV', 'Tuvalu', 'TUV'),
    ('UG', 'Uganda', 'UGA'),
    ('UA', 'Ukraine', 'UKR'),
    ('AE', 'United Arab Emirates', 'ARE'),
    ('GB', 'United Kingdom', 'GBR'),
    ('UM', 'United States minor outlying islands', 'UMI'),
    ('UY', 'Uruguay', 'URY'),
    ('UZ', 'Uzbekistan', 'UZB'),
    ('VU', 'Vanuatu', 'VUT'),
    ('VA', 'Vatican City State', 'VAT'),
    ('VE', 'Venezuela', 'VEN'),
    ('VN', 'Vietnam', 'VNM'),
    ('VG', 'Virgin Islands (British)', 'VGB'),
    ('VI', 'Virgin Islands (U.S.)', 'VIR'),
    ('WF', 'Wallis and Futuna Islands', 'WLF'),
    ('EH', 'Western Sahara', 'ESH'),
    ('YE', 'Yemen', 'YEM'),
    ('YU', 'Yugoslavia', NULL),
    ('ZR', 'Zaire', NULL),
    ('ZM', 'Zambia', 'ZMB');

insert into STUDIES (name) values
    ('Medicine / Nursing'),
    ('Chemistry'),
    ('Physics'),
    ('Mathematics / Statistics'),
    ('Geology'),
    ('Veterinary'),
    ('Engineering'),
    ('Architecture'),
    ('Business Management'),
    ('Economics'),
    ('Law Studies'),
    ('Foreign Languages / Philology'),
    ('History / Philosophy'),
    ('Social Studies'),
    ('Education'),
    ('Other'),
    ('Unknown');

insert into FACULTY (name) values
    ('Campus San Francisco'),
    ('Campus Rio Ebro'),
    ('Campus Veterinaria'),
    ('USJ - Universidad San Jorge'),
    ('Campus de Huesca'),
    ('Campus de Teruel'),
    ('Campus de Jaca'),
    ('Campus de La Almunia'),
    ('Other'),
    ('Unknown');

insert into SEMESTER (id, year, num_semester, start_date, end_date, name) values
    (201401, 2014, 1, '2014-09-01', '2015-01-31', 'First semester course 2014/2015'),
    (201402, 2014, 2, '2015-02-01', '2015-06-30', 'Second semester course 2014/2015'),
    (201501, 2015, 1, '2015-09-01', '2016-01-31', 'First semester course 2015/2016'),
    (201502, 2015, 2, '2016-02-01', '2016-06-30', 'Second semester course 2015/2016'),
    (201601, 2016, 1, '2016-09-01', '2017-01-31', 'First semester course 2016/2017'),
    (201602, 2016, 2, '2017-02-01', '2017-06-30', 'Second semester course 2016/2017');
